steps:
  # Build and deploy from backend folder
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd backend && gcloud run deploy sigma-sync-worker \
          --source . \
          --region europe-west1 \
          --allow-unauthenticated \
          --memory 4Gi \
          --cpu 2 \
          --timeout 540 \
          --set-env-vars="GCS_BUCKET=sigma-docs-repository"

options:
  logging: CLOUD_LOGGING_ONLY
