steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sigma-whatsapp', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sigma-whatsapp']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'sigma-whatsapp'
      - '--image'
      - 'gcr.io/$PROJECT_ID/sigma-whatsapp'
      - '--region'
      - 'europe-west1'
      - '--memory'
      - '1Gi'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3000'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '900s'
