FROM devlikeapro/waha:latest

ENV WHATSAPP_HOOK_URL=https://sigma-whatsapp-webhook-p2hbneatwa-ew.a.run.app/webhook
ENV WHATSAPP_HOOK_EVENTS=message
ENV WAHA_PRINT_QR=true
ENV WHATSAPP_API_PORT=3000
ENV WHATSAPP_API_KEY=
ENV WAHA_DASHBOARD_ENABLED=true

EXPOSE 3000
