FROM devlikeapro/waha:latest

ENV WHATSAPP_HOOK_URL=https://sigma-whatsapp-webhook-71025980302.europe-west1.run.app/webhook
ENV WHATSAPP_HOOK_EVENTS=message
ENV WAHA_PRINT_QR=true
ENV WHATSAPP_API_PORT=3000

EXPOSE 3000
